#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.'
    false;
)
